
<div class="main-panel">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="#">Fabricante</a>
                
<?php

    $resultado = "";    
    
    $fabricante = new Fabricante();
    $helper = new Helper();
    $fabricanteController = new FabricanteController();
    $btnCadastrar = filter_input(INPUT_POST, 'btnCadastrar', FILTER_SANITIZE_STRING);
    
    if($btnCadastrar){
       $fabricante->setTitulo(filter_input(INPUT_POST, 'txtTitulo', FILTER_SANITIZE_STRING));
       $url = $helper->Name($fabricante->getTitulo());
       $fabricante->setUrl($url);
       $fabricante->setData(date('Y-m-d H:i:s'));
       if($fabricanteController->Cadastrar($fabricante)){
           echo 'Cadastrou';
       } else {
           echo 'erro';
       }
       
       var_dump($fabricante);
    }
    
?>

            </div>
            <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>


    <div class="content">
        <div class="container-fluid">
            <div class="row">              

                    
                <div class="col-lg-12 col-md-7">                    
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Fabricante</h4>
                        </div>
                        <div class="content">
                            <form method="post">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Título</label>
                                            <input type="text" name="txtTitulo" class="form-control border-input" placeholder="Nome do Fabricante">
                                        </div>
                                    </div>
                                </div>

                                
                                <div class="row">
                                    <div class="col-md-12">
                                        <?php echo $resultado; ?>
                                    </div>
                                    
                                </div>                               


                                <div class="text-center">
                                    <input type="submit" class="btn btn-success btn-fill btn-wd" name="btnCadastrar" value="Cadastrar">
                                    <a href="?pagina=listarFabricante" class="btn btn-info btn-fill btn-wd">Listar Fabricante</a>
                                </div>
                                
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>

