<?php
//intanciando os objetos
$fabricanteController = new FabricanteController();
$fabricante = new Fabricante();
$helper = new Helper();

//mostra a mensagem verdadeiro ou falso na hora do cadastro
$resultado = "";
$titulo = "";
$status = "";
$descricao = "";
$data = "";

$btnExcluir = filter_input(INPUT_GET, "del", FILTER_SANITIZE_NUMBER_INT);
if($btnExcluir):    
    if ($categoriaController->Excluir($btnExcluir)):
        $resultado = "<div class=\"alert alert-success\">A categoria </b> foi removido com sucesso</div>";
    else:
        $resultado = "<div class=\"alert alert-danger\">Erro ao remover a categoria</div>";
    endif;
endif;

$btnCadastrar = filter_input(INPUT_POST, "btnCadastrar", FILTER_SANITIZE_STRING);
if ($btnCadastrar):
    $categoria->setCod(filter_input(INPUT_GET, "cod", FILTER_SANITIZE_NUMBER_INT));
    $categoria->setTitulo(filter_input(INPUT_POST, "txtTitulo", FILTER_SANITIZE_STRING));
    $txtUrl = Helper::Name($categoria->getTitulo());
    $categoria->setUrl($txtUrl);
    $categoria->setStatus(filter_input(INPUT_POST, "slStatus", FILTER_SANITIZE_NUMBER_INT));
    $categoria->setDescricao(filter_input(INPUT_POST, "txtDescricao", FILTER_SANITIZE_STRING));    
    $categoria->setData(date('Y-m-d H:i:s'));
    

    if ($categoriaController->Atualizar($categoria)):
        $resultado = '<div class="alert alert-info">
        <button type="button" aria-hidden="true" class="close">×</button>
        <span><b> Atualizado com sucesso - </b></span>
        </div>';
    else:
        $resultado = '<div class="alert alert-danger">
        <button type="button" aria-hidden="true" class="close">×</button>
        <span><b> Erro ao atualizar, tente mais tarde - </b></span>
        </div>';
    endif; 
endif;


//listando os usuarios
$listaFabricante = $fabricanteController->ListaFabricante();

?>

<div class="main-panel">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="#">Categoria Cadastrada</a>
            </div>
            <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>


    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Lista de Fabricante</h4>

                        </div>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                                <thead>
                                    <th>ID</th>
                                    <th>Titulo</th>
                                    <th>Descricao</th>
                                    <th>Data</th>
                                    <th>Atualizar</th>
                                    <th>Excluir</th>                                    
                                </thead>
                                <tbody>
                                    <?php
                                        if($listaFabricante == null):
                                            echo '<td colspan="7">Não existe nenhum fabricante cadastrado nesse momento</td';
                                        else:
                                            foreach($listaFabricante as $fab):
                                    ?>
                                    <tr>
                                    
                                        <td><?= $fab->getCod();?></td>
                                        <td><?= $fab->getTitulo();?></td>
                                        <td><?= $fab->getUrl();?></td>
                                        <td><?= $helper->converteData($fab->getData());?></td>
                                        <td><a href="?pagina=listarFabricante&cod=<?= $fab->getCod();?>" class="btn btn-sm btn-info btn-icon"><i class="fa ti-slice"></i></a></td>
                                        <td><a href="?pagina=listarFabricante&del=<?= $fab->getCod();?>" title="Excluir" class="btn btn-sm btn-danger btn-icon"><i class="fa ti-trash"></i></a></td>
                                        
                                    
                                    </tr>
                                    <?php
                                            endforeach;
                                        endif;
                                    ?>
                                    

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12">
                <?php
                    //retorna dado da Categoria
                    $cod = filter_input(INPUT_GET, 'cod', FILTER_SANITIZE_NUMBER_INT);

                    $retornaFabricante = $fabricanteController->retornaFabricante($cod);
                    if($retornaFabricante == null):
                        else:
                            $titulo = $retornaFabricante->getTitulo();
                            
                            
                    
                    ?>    
                    

                        <div class="card">
                            <div class="header">
                                <h4 class="title">Fabricante</h4>
                               
                            </div>
                            <div class="content">
                                <form method="post">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Título</label>
                                                <input type="text" name="txtTitulo" class="form-control border-input" placeholder="Título da Categoria" value="<?=$titulo ?>">
                                            </div>
                                        </div>                                    
                                    <div class="row">                                                                 
                                </div>   
                                    

                                    <div class="row">
                                        <div class="col-md-12">
                                            <?php echo $resultado; ?>
                                        </div>
                                    </div>                              

                                    <div class="text-center">
                                        <input type="submit" class="btn btn-success btn-fill btn-wd" name="btnCadastrar" value="Atualizar">
                                    </div>
                                    <div class="clearfix"></div>
                                </form>
                            </div>
                        </div>
                <?php
                endif;
                ?>
                </div>


            </div>
        </div>
    </div>
    
   